# Generated by Django 6.0.5 on 2026-05-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='category',
            field=models.CharField(),
        ),
    ]
