# Generated by Django 6.0.6 on 2026-06-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
