# Generated by Django 6.0.5 on 2026-05-29 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField()),
                ("text", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(5)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Коментарі",
                "verbose_name_plural": "Коментарі",
            },
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name": "Замовлення"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Назви кімнат"},
        ),
        migrations.AlterModelOptions(
            name="roomcategory",
            options={"verbose_name": "Категорія кімнати"},
        ),
    ]
